/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function get_spells(a: number, b: number, c: number): void;
export function __wbg_stats_free(a: number): void;
export function __wbg_get_stats_ranged_ap(a: number): number;
export function __wbg_set_stats_ranged_ap(a: number, b: number): void;
export function __wbg_get_stats_agi(a: number): number;
export function __wbg_set_stats_agi(a: number, b: number): void;
export function __wbg_get_stats_crit(a: number): number;
export function __wbg_set_stats_crit(a: number, b: number): void;
export function __wbg_get_stats_hit(a: number): number;
export function __wbg_set_stats_hit(a: number, b: number): void;
export function __wbg_get_stats_haste(a: number): number;
export function __wbg_set_stats_haste(a: number, b: number): void;
export function get_stats(a: number, b: number): number;
export function run_sim(a: number, b: number): number;
export function __wbg_summary_free(a: number): void;
export function __wbg_get_summary_dps(a: number): number;
export function __wbg_set_summary_dps(a: number, b: number): void;
export function __wbg_get_summary_pet_dps(a: number): number;
export function __wbg_set_summary_pet_dps(a: number, b: number): void;
export function __wbg_get_summary_auto_shot_casts(a: number): number;
export function __wbg_set_summary_auto_shot_casts(a: number, b: number): void;
export function __wbg_get_summary_auto_shot_crits(a: number): number;
export function __wbg_set_summary_auto_shot_crits(a: number, b: number): void;
export function __wbg_get_summary_auto_shot_dps(a: number): number;
export function __wbg_set_summary_auto_shot_dps(a: number, b: number): void;
export function __wbg_get_summary_steady_shot_casts(a: number): number;
export function __wbg_set_summary_steady_shot_casts(a: number, b: number): void;
export function __wbg_get_summary_steady_shot_crits(a: number): number;
export function __wbg_set_summary_steady_shot_crits(a: number, b: number): void;
export function __wbg_get_summary_steady_shot_dps(a: number): number;
export function __wbg_set_summary_steady_shot_dps(a: number, b: number): void;
export function __wbg_get_summary_multi_shot_casts(a: number): number;
export function __wbg_set_summary_multi_shot_casts(a: number, b: number): void;
export function __wbg_get_summary_multi_shot_crits(a: number): number;
export function __wbg_set_summary_multi_shot_crits(a: number, b: number): void;
export function __wbg_get_summary_multi_shot_dps(a: number): number;
export function __wbg_set_summary_multi_shot_dps(a: number, b: number): void;
export function __wbg_get_summary_arcane_shot_casts(a: number): number;
export function __wbg_set_summary_arcane_shot_casts(a: number, b: number): void;
export function __wbg_get_summary_arcane_shot_crits(a: number): number;
export function __wbg_set_summary_arcane_shot_crits(a: number, b: number): void;
export function __wbg_get_summary_arcane_shot_dps(a: number): number;
export function __wbg_set_summary_arcane_shot_dps(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
